"""Cost table: $ per 1M output tokens from measured throughput and user-confirmed hourly prices.

``$/1M output tokens = usd_per_hour / (output_tok_s * 3600) * 1e6``. A target's price is only
used if every line item is ``confirmed = true`` with a positive price; otherwise the cost column
stays empty and the row says why, so an unconfirmed guess can never reach a reported number.
"""

from __future__ import annotations

import tomllib
from collections.abc import Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from bench.report import Run, write_csv

COST_COLUMNS = (
    "target",
    "concurrency",
    "output_tok_s",
    "slo_attainment",
    "usd_per_hour",
    "usd_per_1m_output_tokens",
    "price_status",
)


@dataclass(frozen=True)
class PriceItem:
    name: str
    usd_per_hour: float
    source: str
    as_of: str
    confirmed: bool


@dataclass(frozen=True)
class TargetPrice:
    target: str
    description: str
    items: tuple[PriceItem, ...]

    @property
    def usd_per_hour(self) -> float:
        return sum(i.usd_per_hour for i in self.items)

    @property
    def confirmed(self) -> bool:
        return bool(self.items) and all(i.confirmed and i.usd_per_hour > 0 for i in self.items)


def load_prices(path: Path) -> dict[str, TargetPrice]:
    data = tomllib.loads(Path(path).read_text())
    prices = {}
    for target, spec in (data.get("targets") or {}).items():
        items = tuple(
            PriceItem(
                name=str(item["name"]),
                usd_per_hour=float(item["usd_per_hour"]),
                source=str(item.get("source", "")),
                as_of=str(item.get("as_of", "")),
                confirmed=bool(item.get("confirmed", False)),
            )
            for item in spec.get("items", [])
        )
        prices[target] = TargetPrice(target, str(spec.get("description", "")), items)
    return prices


def usd_per_million_tokens(usd_per_hour: float, output_tok_s: float | None) -> float | None:
    if not output_tok_s or output_tok_s <= 0:
        return None
    return usd_per_hour / (output_tok_s * 3600.0) * 1_000_000


def price_status(price: TargetPrice | None) -> str:
    if price is None:
        return "missing"
    return "confirmed" if price.confirmed else "unconfirmed"


def cost_rows(runs: Sequence[Run], prices: dict[str, TargetPrice]) -> list[dict[str, Any]]:
    rows = []
    for run in runs:
        price = prices.get(run.target)
        status = price_status(price)
        usd_per_hour = price.usd_per_hour if status == "confirmed" else None
        for level in run.rows:
            per_million = (
                usd_per_million_tokens(usd_per_hour, level.get("output_tok_s"))
                if usd_per_hour is not None
                else None
            )
            rows.append(
                {
                    "target": run.target,
                    "concurrency": level["concurrency"],
                    "output_tok_s": level.get("output_tok_s"),
                    "slo_attainment": level.get("slo_attainment"),
                    "usd_per_hour": usd_per_hour,
                    "usd_per_1m_output_tokens": per_million,
                    "price_status": status,
                }
            )
    return rows


def best_rows(rows: Sequence[dict[str, Any]], slo_min_attainment: float) -> list[dict[str, Any]]:
    """Per target: the peak-throughput level, and the best level that still meets the SLO."""
    out = []
    for target in dict.fromkeys(r["target"] for r in rows):
        levels = [r for r in rows if r["target"] == target and r.get("output_tok_s")]
        if not levels:
            continue
        out.append({**max(levels, key=lambda r: r["output_tok_s"]), "basis": "peak throughput"})
        within = [
            r
            for r in levels
            if r.get("slo_attainment") is not None and r["slo_attainment"] >= slo_min_attainment
        ]
        if within:
            basis = f"best with SLO attainment >= {slo_min_attainment:.0%}"
            out.append({**max(within, key=lambda r: r["output_tok_s"]), "basis": basis})
    return out


def write_cost_report(
    rows: Sequence[dict[str, Any]],
    best: Sequence[dict[str, Any]],
    prices: dict[str, TargetPrice],
    out_dir: Path,
) -> tuple[Path, Path]:
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    csv_path = out_dir / "cost.csv"
    write_csv(csv_path, rows, COST_COLUMNS)

    def money(value: float | None, digits: int) -> str:
        return "n/a" if value is None else f"${value:,.{digits}f}"

    def number(value: float | None, spec: str) -> str:
        return "n/a" if value is None else format(value, spec)

    lines = [
        "# Cost per 1M output tokens",
        "",
        "Generated by `python -m bench cost` from the runs' `summary.csv` and the prices below.",
        "",
        "| Target | Basis | Concurrency | Output tok/s | $/hour | $ per 1M output tokens |",
        "|---|---|---:|---:|---:|---:|",
    ]
    for r in best:
        cost = money(r["usd_per_1m_output_tokens"], 3)
        if r["usd_per_1m_output_tokens"] is None:
            cost += f" ({r['price_status']} price)"
        lines.append(
            f"| {r['target']} | {r['basis']} | {r['concurrency']} "
            f"| {number(r['output_tok_s'], ',.1f')} | {money(r['usd_per_hour'], 3)} | {cost} |"
        )
    lines += ["", "## Prices used", ""]
    targets = dict.fromkeys(r["target"] for r in rows)
    for target in targets:
        price = prices.get(target)
        if price is None:
            lines.append(f"- **{target}**: no entry in the price file")
            continue
        lines.append(f"- **{target}** ({price_status(price)}): {price.description}")
        for item in price.items:
            state = "confirmed" if item.confirmed else "NOT confirmed"
            lines.append(
                f"  - {item.name}: ${item.usd_per_hour:,.4f}/h, {state}, "
                f"source: {item.source or 'n/a'}, as of: {item.as_of or 'n/a'}"
            )
    md_path = out_dir / "cost.md"
    md_path.write_text("\n".join(lines) + "\n")
    return csv_path, md_path
